### ISSUE TITLE
FInd a better way to identify if the notebook is running in colab

### ISSUE THREAD

**Issue by ulf1** [kmedian/colabtweak#1]
FIle: https://github.com/kmedian/colabtweak/blob/master/colabtweak/load_data_path.py

one of the first rows 

```
...
if os.getcwd() == '/content':
    ...
```

This is used to identify if the notebook is running in colab because `/content` might look a bit unusual as a project folder (A project folder might look like `/Users/myname/GitHub/SomeProject/mynotebooks`)

Is there another way to identify if the notebook is running in Colab?

**Comment by colaboratory-team** [comment]
A simple way to check is to look for `google.colab` in `sys.modules`, e.g.,

```
import sys
if 'google.colab' in sys.modules:
  print ('Running in Colab')
```

**Comment by ulf1** [comment]
https://github.com/kmedian/colabtweak/releases/tag/0.1.1
